config/routes.rb
Rails.application.routes.draw do
  resources :scholarships
  root 'pages#home'
  get 'pages/events'
  get 'pages/scholarships'
  get 'pages/myaccount'
  get 'pages/project'
  get 'pages/home'
  get 'pages/account'
  get 'pages/signup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scholarship.rb
class Scholarship < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def events
  end

  def scholarships
    @scholarships = Scholarship.all
  end

  def myaccount 
  end

  def project
  end

  def signup
  end


  def home
  end

  def account
  end
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]

  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
  end

  # GET /scholarships/new
  def new
    @scholarship = Scholarship.new
  end

  # GET /scholarships/1/edit
  def edit
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(scholarship_params)

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship }
      else
        format.html { render :new }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarships/1
  # PATCH/PUT /scholarships/1.json
  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship }
      else
        format.html { render :edit }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to scholarships_url, notice: 'Scholarship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_params
      params.require(:scholarship).permit(:hours, :name, :description, :relevance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/pages/events.html.erb
<!DOCTYPE html>
<!-- Template by Quackit.com -->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Portal 1</title>

    <!-- Bootstrap 4 CSS. This is for the alpha 3 release of Bootstrap 4. This should be updated when Bootstrap 4 is officially released. -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
      
    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="css/custom.css" rel="stylesheet">
    
    <!-- For icons -->
    <link href="css/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation-->
    <!-- Navigation-->
    <nav id="topNav" class="navbar navbar-full navbar-static-top navbar-dark bg-inverse m-b-1">
        <button class="navbar-toggler hidden-md-up pull-right" type="button" data-toggle="collapse" data-target="#navbar">
            &#9776;
        </button>
        <div class="navbar-brand"><%= link_to "V-Service", pages_home_path %></div>
        <div class="collapse navbar-toggleable-sm" id="navbar">
            <ul class="nav navbar-nav" id="nav">
                <!--<li><%= link_to "Home", pages_home_path %></li>
                <li><%= link_to "Scholarships", pages_scholarships_path %></li>
                <li><%= link_to "My Account", pages_myaccount_path%></li>
                <li class="break"><%= link_to "Project", pages_project_path%></li>
                <li><%= link_to "Events", pages_events_path %></li>-->
            
            <!-- Search -->
            <form class="form-inline pull-xs-right">
                <input class="form-control" type="text" placeholder="Search">
                <button class="btn btn-secondary" type="submit">Search</button>
            </form>

            </ul>
        </div>
    </nav>
    

<div class="container-fluid">

		<!-- Left Column -->
		<div class="col-sm-3">

			<!-- List-Group Panel -->
			<div class="card">

				<div class="list-group list-group-flush">
					
					
				</div>
			</div>

				
		</div><!--/Left Column-->
  
  
		<!-- Center Column -->
		<div class="col-sm-6">
		
			<!-- Alert -->
			<div class="alert alert-success alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<strong>Welcome to the Events Page!</strong> 
			</div>		
		
			<!-- Articles -->
			<div class="row">
				<article class="col-xs-12">
					<h2>Events Near Me</h2>
<div class="mapouter"><div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=Community%20Service%20Valdosta&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.pureblack.de">homepage kosten</a></div><style>.mapouter{text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style></div>
						<li class="list-inline-item"><a href="#">Today</a></li>
						<li class="list-inline-item"><a href="#"><span class="glyphicon glyphicon-comment"></span> 2 Comments</a></li>
						<li class="list-inline-item"><a href="#"><span class="glyphicon glyphicon-share"></span> 8 Shares</a></li>
					</ul>
				</article>
			</div>
			<hr>
			<div class="row">
				<article class="col-xs-12">
					<h2>Calendar of Monthly Events</h2>
<iframe src="https://calendar.google.com/calendar/embed?src=cqje4ac2v4sba0t2g113o5nui0%40group.calendar.google.com&ctz=America%2FNew_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>						<li class="list-inline-item"><a href="#"><span class="glyphicon glyphicon-comment">
					</ul>
				</article>
			</div>
			<hr>      

			<hr>
		</div><!--/Center Column-->


	  <!-- Right Column -->
	  <div class="col-sm-3">


 
			<!-- Progress Bars -->
			<div class="card">
				<div class="card-header p-b-0">
					<h5 class="card-title">
						<i class="fa fa-tachometer" aria-hidden="true"></i> 
						Hours Tracker
					</h5>
				</div>
				<div class="card-block">
                    <div class="text-xs-center" id="progress-caption-1">Boys & Girls Club &hellip; 120/120</div>
                    <progress class="progress progress-success" value="100" max="100" aria-describedby="progress-caption-1"></progress>
                    <div class="text-xs-center" id="progress-caption-2">Greater Valdosta United Way &hellip; 100/120</div>
                    <progress class="progress progress-info" value="80" max="100" aria-describedby="progress-caption-2"></progress>
                    <div class="text-xs-center" id="progress-caption-3">American Red Cross &hellip; 50/120</div>
                    <progress class="progress progress-warning" value="45" max="100" aria-describedby="progress-caption-3"></progress>
                    <div class="text-xs-center" id="progress-caption-4"> Valdosta Soup Kitchen &hellip; 35/120</div>
                    <progress class="progress progress-danger" value="35" max="100" aria-describedby="progress-caption-4"></progress>
				</div>
			</div>

			<!-- Carousel --> 

			<div id="side-carousel" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">

				</ol>
				<div class="carousel-inner" role="listbox">

		
						</div>
					</div>


				</div>
				<!-- /.row -->	
			</div>
        </div>
        
        <div class="small-print">
        	<div class="container">
        		<p><a href="#">Terms &amp; Conditions</a> | <a href="#">Privacy Policy</a> | <a href="#">Contact</a></p>
        		<p>Copyright &copy; VService.com 2019 </p>
        	</div>
        </div>
	</footer>

	
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>

    <!-- Tether -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>

    <!-- Bootstrap 4 JavaScript. This is for the alpha 3 release of Bootstrap 4. This should be updated when Bootstrap 4 is officially released. -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>

    <!-- Initialize Bootstrap functionality -->
    <script>
    // Initialize tooltip component
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
    // Initialize popover component
    $(function () {
      $('[data-toggle="popover"]').popover()
    })
    </script> 
    
	<!-- Placeholder Images -->
	<script src="js/holder.min.js"></script>
	
</body>

</html>

app/views/pages/home.html.erb
<!DOCTYPE HTML>
<!--
	Telephasic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Telephasic by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	</head>
	<body class="homepage is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div id="header" class="container">

						<!-- Logo -->
            <h1 id="logo"><%= link_to "Home", pages_home_path %></h1>

						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li>
                    <%= link_to "Scholarships", pages_scholarships_path %> 
										<ul>
											<li><a href="#">Lorem ipsum dolor</a></li>
											<li><a href="#">Magna phasellus</a></li>
											<li><a href="#">Etiam dolore nisl</a></li>
											<li>
												<a href="#">Phasellus consequat</a>
												<ul>
													<li><a href="#">Lorem ipsum dolor</a></li>
													<li><a href="#">Phasellus consequat</a></li>
													<li><a href="#">Magna phasellus</a></li>
													<li><a href="#">Etiam dolore nisl</a></li>
												</ul>
											</li>
											<li><a href="#">Veroeros feugiat</a></li>
										</ul>
									</li>
                  <li><%= link_to "My Account", pages_myaccount_path%></li>
                  <li class="break"><%= link_to "Project", pages_project_path%></li>
                  <li><%= link_to "Events", pages_events_path %></li>
								</ul>
							</nav>

					</div>

					<!-- Hero -->
						<section id="hero" class="container">
							<header>
								<h2>V-Service is your community
								<br />
								service outreach platform </h2>
							</header>
							<p> Designed to reward you and give you inner peace
							<br />
							for taking care of your community!</p>
							<ul class="actions">
                <li><%= link_to "See Events Near Me", pages_events_path %></li>
							</ul>
						</section>

				</div>

			<!-- Features 1 -->
				<div class="wrapper">
					<div class="container">
						<div class="row">
							<section class="col-6 col-12-narrower feature">
								<div class="image-wrapper first">
									<a href="#" class="image featured first"><img src="images/pic01.jpg" alt="" /></a>
								</div>
								<header>
									<h2>See Scholarships that support <br />
									your volunteer interests</h2>
								</header>
                <p><strong><b>V-Service</b></strong> shows you scholarships that you are eligible for
                depending on the number of hours that you have volunteered.</p>
								<ul class="actions">
                  <li><%= link_to "View Scholarships", pages_scholarships_path %></li>
								</ul>
							</section>
							<section class="col-6 col-12-narrower feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="images/pic02.jpg" alt="" /></a>
								</div>
								<header>
									<h2>Organize your time with <br />
									V-Service''s scheduling tool.</h2>
								</header>
								<ul class="actions">
                  <p>View your volunteer hours  
                  and more viewing your account page. </p>
                  <li><%= link_to "Open My Account", pages_myaccount_path %><li/>
								</ul>
							</section>
						</div>
					</div>
				</div>

			<!-- Promo -->
				<div id="promo-wrapper">
					<section id="promo">
						<h2 style="color:black">Set and achieve your scholarship goals with our project board app. <%= link_to "| Open Project Board", pages_project_path %></h2>
            
					</section>
				</div>

			<!-- Features 2 -->
				<div class="wrapper">
					<section class="container">
						<header class="major">
              <h2>Streamlining Scholarship Applications and Volunteer Hours</h2>
              <p>V-Service is an app that allows people to apply for scholrships and 
              log their community service hours.</p>
						</header>
						<div class="row features">
							<section class="col-4 col-12-narrower feature">
								<div class="image-wrapper first">
									<a href="#" class="image featured"><img src="images/pic03.jpg" alt="" /></a>
								</div>
                <p>search for scholarships that align with your 
                volunteer service hours</p>
							</section>
							<section class="col-4 col-12-narrower feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="images/pic04.jpg" alt="" /></a>
								</div>
                <p>organize your scholarship and service  
                using the project dash board</p>
							</section>
							<section class="col-4 col-12-narrower feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="images/pic05.jpg" alt="" /></a>
								</div>
                <p>view volunteer events near you  
                on the events page</p>
							</section>
						</div>
						<ul class="actions major">
              <li><%= link_to "View Your Service Hours", pages_home_path %></li>
						</ul>
					</section>
				</div>

			<!-- Footer -->
				<div id="footer-wrapper">
					<div id="footer" class="container">
						<header class="major">
							<h2>Contact Us</h2>
              <p>Do you have questions about how to use our site? Reach out to us!<br /> </p>
						</header>
						<div class="row">
							<section class="col-6 col-12-narrower">
								<form method="post" action="#">
									<div class="row gtr-50">
										<div class="col-6 col-12-mobile">
											<input name="name" placeholder="Name" type="text" />
										</div>
                    <div class="col-6 col-12-mobile">
											<input name="email" placeholder="Email" type="text" />
										</div>
										<div class="col-12">
											<textarea name="message" placeholder="Message"></textarea>
										</div>
										<div class="col-12">
											<ul class="actions">
												<li><input type="submit" value="Send Message" /></li>
												<li><input type="reset" value="Clear form" /></li>
											</ul>
										</div>
									</div>
								</form>
							</section>
						</div>
					</div>
					<div id="copyright" class="container">
						<ul class="menu">
							<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</div>
				</div>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/pages/myaccount.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Login</title>
  </head>

  <body>

    <div class = "container">
      <h1 class="display-1">Login</h1>
      <hr>
      <br>


      <div class="container">
        <form name="myLoginForm"> 
          <div>
            <label>Email</label>
            <input type="email" placeholder="sample@email.com" name ="email">
          </div>

          <label>Password</label>
            <input type="password"  name ="password">
          </div>

          <br>
         <button class="submit">
          <%=link_to "Login", pages_account_path %>
            </button>
           <p class="lead" style="padding-top:25px">Don't have an account?</p>
           <li><%= link_to "Create One Now", pages_signup_path%></li>


        </form>
        <hr>
      </div>
    </div>
  </body>
</html>

app/views/pages/project.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="project.css" type="text/css" rel="stylesheet"> 
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>Login</title>
  </head>
<body>

<div id="header" class="container">
    <!-- Nav -->
        <nav id="nav">
            <ul>
                <li><%= link_to "Home", pages_home_path %></li>
                <li><%= link_to "Scholarships", pages_scholarships_path %></li>
                <li><%= link_to "My Account", pages_myaccount_path%></li>
                <li class="break"><%= link_to "Project", pages_project_path%></li>
                <li><%= link_to "Events", pages_events_path %></li>
            </ul>
        </nav>
</div>

<div class="container-fluid bg-gradient p-5">
      <div class="row m-auto text-center w-75">
        
        <div class="col-4 princing-item red">
          <div class="pricing-divider ">
              <h3 class="text-light">Upcoming events</h3>
            <h4 class="my-0 display-2 text-light font-weight-normal mb-3"> Feb</h4>
             <svg class='pricing-divider-img' enable-background='new 0 0 300 100' height='100px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='300px' x='0px' xml:space='preserve' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' y='0px'>
          <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729
	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729
	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716
	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
          <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428
	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#FFFFFF'></path>
        </svg>
          </div>
          <div class="card-body bg-white mt-0 shadow">
            <ul class="list-unstyled mb-5 position-relative">
              <li><b>Feb 12/19</b> Boys and Girls Club</li>
              <li><b>Feb 16/19</b> Greater Valdosta United Way</li>
            </ul>
          </div>
        </div>
       

        
        
        <div class="col-4 princing-item blue">
          <div class="pricing-divider ">
              <h3 class="text-light">Attending Events</h3>
            <h4 class="my-0 display-2 text-light font-weight-normal mb-3"> Feb </h4>
             <svg class='pricing-divider-img' enable-background='new 0 0 300 100' height='100px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='300px' x='0px' xml:space='preserve' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' y='0px'>
          <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729
	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729
	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716
	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
          <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428
	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#FFFFFF'></path>
        </svg>
          </div>

          <div class="card-body bg-white mt-0 shadow">
            <ul class="list-unstyled mb-5 position-relative">
              <li><b>Feb 10/19</b> Valdosta Soup Kitchen</li>
              <li><b>Feb 28/19</b> American Red Cross</li>
            </ul>
          </div>
        </div>
               
        
  
        
        
         
        <div class="col-4 princing-item green">
          <div class="pricing-divider ">
              <h3 class="text-light">Events Attended</h3>
            <h4 class="my-0 display-2 text-light font-weight-normal mb-3"> Mar</h4>
             <svg class='pricing-divider-img' enable-background='new 0 0 300 100' height='100px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='300px' x='0px' xml:space='preserve' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' y='0px'>
          <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729
	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729
	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716
	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
          <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428
	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#FFFFFF'></path>
        </svg>
          </div>

          <div class="card-body bg-white mt-0 shadow">
            <ul class="list-unstyled mb-5 position-relative">
              <li><b>Mar 2/19</b> Red Cross shelter</li>
              <li><b>Mar 8/19</b> Creek Rescue</li>  
            </ul>
          </div>
        </div>
               
         
        
        
        
        
      </div>
    </div>
    </body>
</html>

app/views/scholarships/edit.html.erb
<h1>Editing Scholarship</h1>

<%= render 'form', scholarship: @scholarship %>

<%= link_to 'Show', @scholarship %> |
<%= link_to 'Back', scholarships_path %>

app/views/scholarships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scholarships</h1>

<table>
  <thead>
    <tr>
      <th>Hours</th>
      <th>Name</th>
      <th>Description</th>
      <th>Relevance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholarships.each do |scholarship| %>
      <tr>
        <td><%= scholarship.hours %></td>
        <td><%= scholarship.name %></td>
        <td><%= scholarship.description %></td>
        <td><%= scholarship.relevance %></td>
        <td><%= link_to 'Show', scholarship %></td>
        <td><%= link_to 'Edit', edit_scholarship_path(scholarship) %></td>
        <td><%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scholarship', new_scholarship_path %>